### ISSUE TITLE
Quantum RPG: Error on level 3 engineer's turn

### ISSUE THREAD

**Issue by cantwellc** [quantumlib/unitary#139]
I hit level 3 and crashed on my Engineer's turn during the next combat, it appears when it is trying to access the H ability. I don't get the same error for the Analyst. Seems to handle level 3, and the addition of Sample just fine. 

Zed turn:
Traceback (most recent call last):
  File "./unitary/examples/quantum_rpg/main_loop.py", line 242, in <module>
    main(game_state.GameState(party=[]))
  File "./unitary/examples/quantum_rpg/main_loop.py", line 238, in main
    main_loop.loop()
  File "./unitary/examples/quantum_rpg/main_loop.py", line 102, in loop
    result = current_battle.loop()
  File "/home/cantwellc/projects/unitary/env/lib/python3.7/site-packages/unitary/examples/quantum_rpg/battle.py", line 190, in loop
    result = self.take_player_turn()
  File "/home/cantwellc/projects/unitary/env/lib/python3.7/site-packages/unitary/examples/quantum_rpg/battle.py", line 123, in take_player_turn
    print(f"{key}) {descriptions[key]}.", file=self.file)
KeyError: 'h'

**Comment by cantwellc** [comment]
Looks like it is missing a description for h
