### ISSUE TITLE
Unitary: popping makes quantum object unusable

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/unitary#21]
Reported by @bartmate 

After popping (measuring) a 1-bit qobject, it behaves differently. First I thought that it will be "set" into the measured value and then I can use it as before. But it seems it is not the case, I cannot use it any more, or at least it will not behave the same way as before. I solved the problem by adding new 1-bit qobjects which are initialized to the measured values.

I think this is uncomfortable. If I cannot use a qobject any more after popping , it would be great, if the library would be able to automatically do this work-around logic.

**Comment by cognigami** [comment]
@bartmate to test on Fox in the Hole.

**Comment by bartmate** [comment]
I deleted the part which always add a new qobject after measurement: see PR #37.

I found two problems:
* The 2nd one is a run-time error. It may or may not be related with the 2nd one.
* The 1st one: It seems there is still some problem with using a 1-bit QObject after a measurement (or maybe my expectation is wrong): The 2nd move is a split which should split the 4th (index=3) hole into 3th and 5th. My expectation is that those 2 holes should have ~.5 - ~.5 probabilites after the split, but it is not the case. The 3th hole has 0 probabilites, while the 5th one has 1.0.  I suspect, this is because the 3rd (index=2) hole was measured beforehand and it fixed the qobject somehow, so later splits cannot modify it.

Please, check.

**1st:**
```
(base) bm@ct:~/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole$ python3 fox_in_a_hole.py -q -fixseed
Quantum Fox-in-a-hole game.
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2

It seems you have lost :-(. Try again.

History:
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Guess: 2
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Moving (SWAP-based) left from position 4.
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Guess: 2
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Splitting (SWAP-based) from position 3 to positions 2 and 4.
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Guess: 2
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Moving (SWAP-based) left from position 4.
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Guess: 2
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Moving (SWAP-based) right from position 3.
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Guess: 2
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Moving (SWAP-based) left from position 4.
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Guess: 2
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Moving (SWAP-based) left from position 3.
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Guess: 2
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Splitting (SWAP-based) from position 3 to positions 2 and 4.
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Guess: 2
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Moving (SWAP-based) left from position 4.
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Guess: 2
State: [0.0, 0.0, 0.0, 1.0, 0.0]
Moving (SWAP-based) right from position 3.
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Guess: 2
State: [0.0, 0.0, 0.0, 0.0, 1.0]
Moving (SWAP-based) left from position 4.
State: [0.0, 0.0, 0.0, 1.0, 0.0]
```

**2nd**
```
(base) bm@ct:~/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole$ python3 fox_in_a_hole.py -q -fixseed
Quantum Fox-in-a-hole game.
Where is the fox? (0-4 or q for quit)
2
Where is the fox? (0-4 or q for quit)
2
Traceback (most recent call last):
  File "/usr/local/google/home/bartmate/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole/fox_in_a_hole.py", line 258, in <module>
    game.run()
  File "/usr/local/google/home/bartmate/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole/fox_in_a_hole.py", line 94, in run
    self.history_append_state()
  File "/usr/local/google/home/bartmate/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole/fox_in_a_hole.py", line 61, in history_append_state
    self.history.append('State: {}'.format(self.state_to_string()))
  File "/usr/local/google/home/bartmate/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole/fox_in_a_hole.py", line 179, in state_to_string
    return str(self.get_probabilities())
  File "/usr/local/google/home/bartmate/01Work/91Unitary/unitary/unitary/examples/fox_in_a_hole/fox_in_a_hole.py", line 168, in get_probabilities
    peek_result = self.state[0].peek(objects=self.state[1],
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/unitary/alpha/quantum_world.py", line 120, in peek
    return self.peek(objects, count, convert_to_enum, rtn_list)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/unitary/alpha/quantum_world.py", line 120, in peek
    return self.peek(objects, count, convert_to_enum, rtn_list)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/unitary/alpha/quantum_world.py", line 120, in peek
    return self.peek(objects, count, convert_to_enum, rtn_list)
  [Previous line repeated 964 more times]
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/unitary/alpha/quantum_world.py", line 101, in peek
    results = self.sampler.run(measure_circuit, repetitions=num_reps)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/work/sampler.py", line 53, in run
    return self.run_sweep(program, param_resolver, repetitions)[0]
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/simulator.py", line 77, in run_sweep
    return list(self.run_sweep_iter(program, params, repetitions))
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/simulator.py", line 111, in run_sweep_iter
    records = self._run(
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/simulator_base.py", line 250, in _run
    act_on_args = self._create_act_on_args(0, qubits)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/simulator_base.py", line 373, in _create_act_on_args
    args_map[q] = self._create_partial_act_on_args(
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/sparse_simulator.py", line 196, in _create_partial_act_on_args
    return act_on_state_vector_args.ActOnStateVectorArgs(
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/_compat.py", line 330, in decorated_func
    return func(*args, **kwargs)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/_compat.py", line 330, in decorated_func
    return func(*args, **kwargs)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/act_on_state_vector_args.py", line 391, in __init__
    self._state = _BufferedStateVector.create(
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/sim/act_on_state_vector_args.py", line 76, in create
    state_vector = qis.to_valid_state_vector(
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/qis/states.py", line 829, in to_valid_state_vector
    state = quantum_state(state_rep, qid_shape, validate=True, dtype=dtype, atol=atol)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/qis/states.py", line 303, in quantum_state
    return QuantumState(data=data, qid_shape=qid_shape, validate=validate, dtype=dtype, atol=atol)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/qis/states.py", line 101, in __init__
    self.validate(dtype=dtype, atol=atol)
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/qis/states.py", line 184, in validate
    validate_normalized_state_vector(
  File "/usr/local/google/home/bartmate/.local/lib/python3.9/site-packages/cirq/qis/states.py", line 897, in validate_normalized_state_vector
    if not np.isclose(norm, 1, atol=atol):
  File "<__array_function__ internals>", line 5, in isclose
  File "/usr/local/google/home/bartmate/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 2364, in isclose
    if all(xfin) and all(yfin):
  File "<__array_function__ internals>", line 5, in all
  File "/usr/local/google/home/bartmate/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2438, in all
    return _wrapreduction(a, np.logical_and, 'all', axis, None, out,
  File "/usr/local/google/home/bartmate/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 85, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/usr/local/google/home/bartmate/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py", line 62, in _all
    return umr_all(a, axis, dtype, out, keepdims)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by bartmate** [comment]
See above.
